apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS
  containers:
    - name: debug
      image: busybox
      command: ["sh", "-c", "echo 'Running as:' && id && echo 'File permissions:' && ls -la /sciclone && sleep 3600"]
      volumeMounts:
        - name: sciclone-volume
          mountPath: /sciclone
  volumes:
    - name: sciclone-volume
      nfs:
        server: 128.239.59.144
        path: /sciclone
