apiVersion: v1
kind: Pod
metadata:
  name: milvus-standalone
  labels:
    app: milvus-standalone
spec:
  restartPolicy: Always
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS

  containers:
    - name: milvus
      image: milvusdb/milvus:v2.2.11
      ports:
        - containerPort: 19530
          name: milvus
      command: ["sh", "-c"]
      args: ["echo 'Starting Milvus container' && mkdir -p /sciclone/geograd/test/milvus/{data,logs,rocksmq,etcd,minio} && cd /milvus && /milvus/bin/milvus run standalone"]
      env:
        - name: DEPLOY_MODE
          value: "standalone"
        - name: ETCD_ENDPOINTS
          value: "localhost:2379"
        - name: MINIO_ADDRESS
          value: "localhost:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: DATA_PATH
          value: "/sciclone/geograd/test/milvus/data"
        - name: ROCKSMQ_PATH
          value: "/sciclone/geograd/test/milvus/rocksmq"
        - name: LOG_PATH
          value: "/sciclone/geograd/test/milvus/logs"
        - name: ETCD_DATA_PATH
          value: "/sciclone/geograd/test/milvus/etcd"
        - name: MINIO_DATA_PATH
          value: "/sciclone/geograd/test/milvus/minio"
        - name: COMMON_STORAGE_TYPE
          value: "local"
      volumeMounts:
        - name: sciclone-volume
          mountPath: /sciclone  # Mount NFS base directory
  volumes:
    - name: sciclone-volume
      nfs:
        server: 128.239.59.144
        path: /sciclone


---
apiVersion: v1
kind: Service
metadata:
  name: milvus
spec:
  ports:
    - port: 19530
      targetPort: 19530
      name: milvus
  selector:
    app: milvus-standalone
  type: ClusterIP
