apiVersion: v1
kind: Pod
metadata:
  name: milvus-standalone
  labels:
    app: milvus-standalone
spec:
  restartPolicy: Always
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS

  containers:
    - name: milvus
      image: milvusdb/milvus:v2.2.11
      ports:
        - containerPort: 19530
          name: milvus
      command: ["sh", "-c"]
      args: ["echo 'Waiting for etcd and MinIO to start...' && sleep 10 && mkdir -p /sciclone/geograd/test/milvus/{data,logs,rocksmq,etcd,minio} && cd /milvus && /milvus/bin/milvus run standalone"]
      env:
        - name: DEPLOY_MODE
          value: "standalone"
        - name: ETCD_ENDPOINTS
          value: "127.0.0.1:2379"
        - name: MINIO_ADDRESS
          value: "127.0.0.1:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: DATA_PATH
          value: "/sciclone/geograd/test/milvus/data"
        - name: ROCKSMQ_PATH
          value: "/sciclone/geograd/test/milvus/rocksmq"
        - name: LOG_PATH
          value: "/sciclone/geograd/test/milvus/logs"
        - name: ETCD_DATA_PATH
          value: "/sciclone/geograd/test/milvus/etcd"
        - name: MINIO_DATA_PATH
          value: "/sciclone/geograd/test/milvus/minio"
        - name: COMMON_STORAGE_TYPE
          value: "local"
      volumeMounts:
        - name: sciclone-volume
          mountPath: /sciclone  # Mount NFS base directory
    - name: etcd
      image: quay.io/coreos/etcd:v3.5.5
      ports:
        - containerPort: 2379
          name: client
      command: ["/usr/local/bin/etcd"]
      args:
        - --data-dir=/sciclone/geograd/test/milvus/etcd
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://127.0.0.1:2379
        - --max-txn-ops=10000
        - --max-request-bytes=33554432
      env:
        - name: ETCD_AUTO_COMPACTION_MODE
          value: "revision"
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1000"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "4294967296" 
      volumeMounts:
        - name: sciclone-volume
          mountPath: /sciclone
    - name: minio
      image: minio/minio:RELEASE.2023-03-20T20-16-18Z
      ports:
        - containerPort: 9000
          name: minio
      command: ["minio"]
      args:
        - server
        - /sciclone/geograd/test/milvus/minio
        - --address
        - 0.0.0.0:9000
        - --console-address
        - 0.0.0.0:9001
      env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
      volumeMounts:
        - name: sciclone-volume
          mountPath: /sciclone
  volumes:
    - name: sciclone-volume
      nfs:
        server: 128.239.59.144
        path: /sciclone


---
apiVersion: v1
kind: Service
metadata:
  name: milvus
spec:
  ports:
    - port: 19530
      targetPort: 19530
      name: milvus
  selector:
    app: milvus-standalone
  type: ClusterIP
