apiVersion: v1
kind: Pod
metadata:
  name: milvus-minio
  namespace: dsmillerrunfol
  labels:
    app: milvus-minio
spec:
  restartPolicy: Always
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS

  containers:
    - name: minio
      image: minio/minio:RELEASE.2023-03-20T20-16-18Z
      ports:
        - containerPort: 9000
          name: minio
        - containerPort: 9001
          name: console
      command: ["sh", "-c"]
      args: ["
        echo 'Creating and setting permissions on required directories...' && 
        mkdir -p /sciclone/geograd/test/milvus/minio && 
        chmod -R 755 /sciclone/geograd/test/milvus/minio && 
        minio server /sciclone/geograd/test/milvus/minio --address 0.0.0.0:9000 --console-address 0.0.0.0:9001
      "]
      env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
      volumeMounts:
        - name: sciclone-volume
          mountPath: /sciclone
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
        limits:
          memory: "12Gi"
          cpu: "4"
  volumes:
    - name: sciclone-volume
      nfs:
        server: 128.239.59.144
        path: /sciclone

---
apiVersion: v1
kind: Service
metadata:
  name: milvus-minio
  namespace: dsmillerrunfol
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: minio
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: milvus-minio
  type: ClusterIP
